### ISSUE TITLE
developer notes?

### ISSUE THREAD

**Issue by davehorner** [erkie/KM-Bubble-Shooter#11]
thanks for sharing and I would like to try it myself.
any help on building notes;  I know this should compile on:
Mac OS X, Windows and Fedora Linux
but I do not see any Makefiles or scripts associated.
Did you use mingw on windows or MSVC?

Later,
--dave
http://dave.thehorners.com/tech-talk/random-tech/219-quake-iii-fun-game-long-time-no-see

**Comment by erkie** [comment]
For some reason I didn't commit these files... Is it for Windows your wanting to try it out?

**Comment by davehorner** [comment]
Yes, I was trying to run it on windows, but I would be happy to try it on
linux or mac.
Thanks for the response and sharing your code.
--dave

**Comment by erkie** [comment]
I've merged a PR with a makefile that I've tested on two different macs, so just follow the instructions in the README and let me know if it works or not. Unfortunately I don't have a Windows or Linux to test this on so I can't guarantee that it will work.

**Comment by davehorner** [comment]
brew install'd and made like a champ.
a party indeed.

great work!
